service: 'magicpearls-v2-apis'
  
frameworkVersion: '3'

plugins: 
    # - serverless-plugin-typescript
    - serverless-add-api-key
    - serverless-domain-manager
    - serverless-esbuild
    - serverless-offline

provider:
    name: aws
    runtime: nodejs18.x
    stage: ${opt:stage, self:custom.defaultStage}
    region: ${opt:region, self:custom.defaultRegion}
    environment:
        CURRENT_AWS_REGION: ${self:provider.region}
        LICENCE_TABLE: 'tbl_licence_key'
    iamRoleStatements:
      - Effect: "Allow"
        Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:BatchGetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
        Resource:
            - arn:aws:dynamodb:*:*:table/${self:provider.environment.LICENCE_TABLE}


functions:
    fetchLicenseKey:
        handler: src/handlers/GetLicenseKey.handler
        events:
            - http:
                  path: license-key-service/{key}
                  method: get
                  private: true 
    fetchBundle:
        handler: src/handlers/GetBundle.handler
        events:
            - http:
                  path: resource/{resource}
                  method: get
                  private: true 
    resetLicenseKey:
        handler: src/handlers/ResetLicenseKey.handler
        events:
            - http:
                  path: license-key-service/{key}/reset
                  method: get
                  private: true 
    activateLicenseKey:
        handler: src/handlers/ActivateLicenseKey.handler
        events: 
            - http:
                  path: license-key-service/{key}/activate
                  method: post
                  private: true 
    expiryLicenseKey:
        handler: src/handlers/ExpiryLicenseKey.handler
        events: 
            - http:
                  path: license-key-service/{key}/is-expired
                  method: post
                  private: true 
                  
custom:
    defaultRegion: ap-south-1
    defaultStage: dev

    customDomain:
        domainName: 'api.magicpearls.in'
        basePath: v2
        stage: ${self:provider.stage}
        createRoute53Record: true
    apiKeys:
        - name: magicpearls-v2-api-key 
